site_name: German school subjects ontology
theme: readthedocs
#theme: mkdocs
nav:
  - Welcome: index.md
#  - Introduction: intro.md
#  - Ontology: ontology.md
#  - Patterns: patterns.md
#  - Versions: versions.md
#  - Contributing: contributing.md
#  - Contact: contact.md
